### ISSUE TITLE
Training Curiosone

### ISSUE THREAD

**Issue by ghost** [curiosone-bot/curiosone-core#107]
How would one train the Curiosone with a different data set?

Also, I find that the project lacks documentation, is the project still active?

**Comment by simonepri** [comment]
Hi @onlyrida, thank you for taking time to open this issue!
The Curiosone project was a school project and its _currently_ not active maintained.

Also it does not use ML techniques so actually there is no way to train it. 🙃
The only thing you can "improve" now is the [semantic network](https://raw.githubusercontent.com/curiosone-bot/curiosone-core/next/src/main/resources/knowledge/CuriosoneSemanticNetwork.txt) that holds relationships between concepts.

You can find the logic for processing texts [here](https://github.com/curiosone-bot/curiosone-core/blob/next/src/main/java/com/github/bot/curiosone/core/workflow/Logic.java).
